### PR TITLE
Added some buttons

### PR DESCRIPTION
**Pull request by Misko-2083**
Used a new code from Manjaro which supports python3.
Added buttons for launching stuff and made it compatible with LL.
Needs some work on the frontend.

### CODE REVIEW

**Comment by linuxlite** [comment]
Has this been tested as working?

**Comment by Misko-2083** [comment]
Yes, it's working.
One thing I noticed is that it sometimes shows a shadow when scrolling the page.
http://i.imgur.com/8hgV6GB.png

**Comment by Misko-2083** [comment]
But not with the blue button
Format: Lite Welcome

**Comment by Misko-2083** [comment]
Small improvements...

**Pull request merged**
